NOTIF-475 UX improvements on user preferences
RedHatInsights/user-preferences-frontend pull request #102
Opened 2022-02-22 19:10 UTC by aferd

2022-02-22 19:18 UTC, aferd commented
![Screen Shot 2022-02-22 at 2 05 53 PM](https://user-images.githubusercontent.com/86322239/155203161-31c9cd07-0175-4fe7-b472-5dbf6b5521d0.png)

2022-02-22 19:38 UTC, josejulio requested changes

2022-02-22 19:38 UTC, josejulio commented on src/PresentationalComponents/Notification/Notification.js
> +              title={`My Notifications | ${bundleDisplayTitle.title}`}
don't forget to update this one too
```suggestion
              title={`My Notifications | ${bundleDisplayTitle}`}
```

2022-02-22 19:38 UTC, josejulio commented on src/PresentationalComponents/Notification/Notification.js
> +              <a href={`/settings/notifications/${bundleName}`}> Settings</a>.
We need to take into account the beta/stable status here. Not sure how it's done here, but you can search for `beta` and see how is handled.

2022-02-22 19:38 UTC, josejulio commented on src/actions.js
> +export const notificationConfigForBundle = (bundleName) =>
So, for the sake of having code where it belongs, I think we should move out this function to a separate place. 

This file have the redux actions, maybe put it on utilities: https://github.com/RedHatInsights/user-preferences-frontend/blob/master/src/Utilities/functions.js

2022-02-22 20:28 UTC, josejulio commented
@aferd there is one failing test - looks like one import could be wrong?

2022-02-23 15:52 UTC, josejulio commented
@karelhala could you take a look? thanks!

2022-03-01 07:44 UTC, karelhala reviewed
Looking good, just a few minor changes and we are golden.

2022-03-01 07:44 UTC, karelhala commented on src/PresentationalComponents/Notification/Notification.js
> +              style={{ paddingBottom: '8px' }}
Can we move this to `scss` file with class?

2022-03-01 07:44 UTC, karelhala commented on src/PresentationalComponents/Notification/Notification.js
> +              <a href={getBaseName(`/settings/notifications/${bundleName}`)}>
We should use `chrome`'s api similiar to how dashboard is doing it https://github.com/RedHatInsights/insights-dashboard/blob/master/src/SmartComponents/Drift/DriftCard.js#L43 this way we won't force page refresh, but rather make it SPA like.

2022-03-01 07:44 UTC, karelhala commented on src/PresentationalComponents/Notification/Notification.js
> +  const bundleDisplayTitle = notificationConfigForBundle(bundleName).title;
You should use safe accessor here
```suggestion
  const bundleDisplayTitle = notificationConfigForBundle(bundleName)?.title;
```

2022-03-03 18:29 UTC, merged